apiVersion: v2
name: flux
description: A Helm chart for Flux
type: application
version: 0.1.0
dependencies:
- name: flux2
  version: "2.12.4"
  repository: "https://fluxcd-community.github.io/helm-charts"
