apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.clusterName }}-vpc-secret
  namespace: {{ .Values.namespace | default "crossplane-system" }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: {{ .Values.global.clusterName }}-vpc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: vpc_data
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.global.clusterName }}/config
        property: vpc
