{{- $region := "us-west-2" }}
{{- if .Values.aws }}
{{- $region = .Values.aws.region | default "us-west-2" }}
{{- end }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ $region }}
      secretsManager:
        forceDeleteWithoutRecovery: true
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secrets-manager-cs
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ $region }}
      secretsManager:
        forceDeleteWithoutRecovery: true
