apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      secretsManager:
        forceDeleteWithoutRecovery: true
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secrets-manager-cs
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      secretsManager:
        forceDeleteWithoutRecovery: true
