apiVersion: v1
kind: Service
metadata:
  name: rust-microservice
spec:
  selector:
    app: rust-microservice
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rust-microservice-preview
spec:
  selector:
    app: rust-microservice
  ports:
    - port: 8080
      targetPort: 8080
