apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-prestage-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ray
    app.kubernetes.io/component: model-prestage
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-worker-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ray
    app.kubernetes.io/component: worker
    app.kubernetes.io/managed-by: {{ .Release.Service }}
