apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: next-js-application
spec:
  components:
    - name: next-js
      type: appmod-service
      properties:
        image: public.ecr.aws/a0m0j3q7/modernengg/nextjs-ui:latest
        image_name: next-js-app
        port: 8080
        replicas: 1
        env:
          - name: API_BASE_URL
            value: "http://rust-app.team-rust.svc.cluster.local:8080"
      traits:
        - type: path-based-ingress
          properties:
            domain: "*.elb.us-west-2.amazonaws.com"
            rewritePath: false
            http:
              /unicorn: 8080
        
