apiVersion: v2
name: spark-operator
description: A Helm chart for Spark Operator with OIDC authentication
type: application
version: 0.1.0
dependencies:
  - name: spark-operator
    version: '2.4.0'
    repository: https://kubeflow.github.io/spark-operator
