{{- if .Values.kubeflow.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeflow-ingress
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    {{- with .Values.kubeflow.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.kubeflow.ingress.className }}
  rules:
  - host: {{ .Values.kubeflow.ingress.host }}
    http:
      paths:
      - path: {{ .Values.kubeflow.ingress.path }}
        pathType: {{ .Values.kubeflow.ingress.pathType }}
        backend:
          service:
            name: centraldashboard
            port:
              number: 80
{{- end }}