apiVersion: v1
kind: Service
metadata:
  name: java-webservice
spec:
  selector:
    app: java-webservice
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-webservice-preview
spec:
  selector:
    app: java-webservice
  ports:
    - port: 8080
      targetPort: 8080
