apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: aws-ddb-table-${{values.table_name}}
  namespace: ${{values.namespace}}
spec:
  components:
    - name: ${{values.table_name}}
      type: ddb-table
      properties:
        name: ${{values.table_name}}
        region: ${{values.region}}
        attributeName: ${{values.attribute_name}}
        attributeType: ${{values.attribute_type}}