# skeleton/manifests/dynamodb.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ${{values.table_name}}
  namespace: ${{values.namespace}}
spec:
  components:
    - name: ${{values.table_name}}
      type: ddb-table
      properties:
        name: ${{values.table_name}}
        environment: ${{values.environment}}
        configuration: ${{values.configuration}}
        region: ${{values.region}}
        attributeName: ${{values.attribute_name}}
        attributeType: ${{values.attribute_type}}