externalSecret:
  enabled: true
  clusterName: peeks-workshop-spoke-prod
  secretStoreRefKind: ClusterSecretStore
  secretStoreRefName: aws-secrets-manager
  secretManagerSecretName: peeks-workshop-hub-cluster/peeks-workshop-spoke-prod
  server: remote
  
  annotations:
    environment: prod
    tenant: tenant1
    
  labels:
    environment: prod
    tenant: tenant1
    fleet_member: prod
    enable_cert_manager: "true"
    enable_external_secrets: "true"
    enable_ingress_nginx: "true"
    enable_metrics_server: "true"
    enable_kyverno: "true"
    enable_ack_ec2: "true"
    enable_ack_eks: "true"
    enable_ack_iam: "true"
