externalSecret:
  enabled: true
  # Values will be overridden by ApplicationSet
  clusterName: "{{ .Values.externalSecret.clusterName | default \"peeks-spoke-prod\" }}"
  secretStoreRefKind: ClusterSecretStore
  secretStoreRefName: aws-secrets-manager
  secretManagerSecretName: "{{ .Values.externalSecret.secretManagerSecretName | default \"peeks-hub-cluster/peeks-spoke-prod\" }}"
  server: remote
  
  annotations:
    environment: prod
    tenant: "{{ .Values.externalSecret.annotations.tenant | default \"tenant1\" }}"
    
  labels:
    environment: prod
    tenant: "{{ .Values.externalSecret.labels.tenant | default \"tenant1\" }}"
    fleet_member: "{{ .Values.externalSecret.labels.fleet_member | default \"prod\" }}"
    enable_cert_manager: "true"
    enable_external_secrets: "true"
    enable_ingress_nginx: "true"
    enable_metrics_server: "true"
    enable_kyverno: "true"
    enable_ack_ec2: "true"
    enable_ack_eks: "true"
    enable_ack_iam: "true"
