gitRepository:
  url: "{{.metadata.annotations.addons_repo_url}}"
  branch: "{{.metadata.annotations.addons_repo_revision}}"

workloadsRepository:
  url: "{{.metadata.annotations.addons_repo_url}}"
  branch: "{{.metadata.annotations.addons_repo_revision}}"

platformAddons:
  path: "{{.metadata.annotations.addons_repo_basepath}}addons"

workloads:
  path: "{{.metadata.annotations.addons_repo_basepath}}apps"

sshRepository:
  enabled: false
