gitRepository:
  url: "https://d15rvat21gcp87.cloudfront.net/user1/platform-on-eks-workshop.git"
  branch: "main"

clusterName: "peeks-hub-cluster"

workloadsRepository:
  url: "https://d15rvat21gcp87.cloudfront.net/user1/platform-on-eks-workshop.git"
  branch: "main"

platformAddons:
  path: "gitops/addons"

workloads:
  path: "gitops/workloads"

sshRepository:
  enabled: false
