apiVersion: v2
name: crossplane
description: Crossplane Helm Chart
type: application
version: 0.1.0
appVersion: "1.17.1"

dependencies:
- name: crossplane
  version: 1.17.1
  repository: https://charts.crossplane.io/stable
