externalSecret:
  enabled: true
  clusterName: spoke-dev
  secretStoreRefKind: ClusterSecretStore
  secretStoreRefName: aws-secrets-manager
  secretManagerSecretNamePrefix: peeks
  server: remote
  
  # annotations:
  #   environment: dev
  #   tenant: tenant1
    
  # labels:
  #   environment: dev
  #   tenant: tenant1
  #   fleet_member: dev
  #   #TODO I think this is not used here, but already stored in the secret
  #   enable_cert_manager: "true"
  #   enable_external_secrets: "true"
  #   enable_ingress_nginx: "true"
  #   enable_metrics_server: "true"
  #   enable_kyverno: "true"
  #   enable_ack_ec2: "true"
  #   enable_ack_eks: "true"
  #   enable_ack_iam: "true"
  #   enable_ack_s3: "true"
  #   enable_kubevela: "true"
