apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-credentials
  namespace: ${{values.namespace}}
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: "0"
  target:
    name: gitlab-credentials
  data:
    - secretKey: GITLAB_USERNAME
      remoteRef:
        key: ${{values.aws_resource_prefix}}-gitlab-pat
        property: username
    - secretKey: GITLAB_TOKEN
      remoteRef:
        key: ${{values.aws_resource_prefix}}-gitlab-pat
        property: token
