# Namespace is now managed by Kro CICDPipeline resource group
# This file is kept for reference but the resource is commented out
# 
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: ${{values.namespace}}
#   labels:
#     app.kubernetes.io/name: ${{values.appname}}
#     app.kubernetes.io/component: cicd-pipeline
