apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/alias: ""
    definition.oam.dev/description: External secret for RDS or standalone relational database instance
  name: external-database-secret
spec:
  workload:
    type: autodetects
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "external-secrets.io/v1"
        	kind:       "ExternalSecret"
        	metadata: name: context.name
        	spec: {
        		data: [
        			{
        				secretKey: "username"
        				remoteRef: {key: parameter.secret_name, property: "username"}
        			},
        			{
        				secretKey: "password"
        				remoteRef: {key: parameter.secret_name, property: "password"}

        			},
        			{
        				secretKey: "host"
        				remoteRef: {key: parameter.secret_name, property: "host"}

        			},
        		]
        		refreshInterval: "1h"
        		secretStoreRef: {
        			kind: "ClusterSecretStore"
        			name: "aws-secrets-manager"
        		}
        		target: {
        			name:           parameter.secret_name
        			creationPolicy: "Owner"
        		}
        	}
        }

        parameter: secret_name: string

