apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  annotations:
    definition.oam.dev/alias: ""
    definition.oam.dev/description: S3 Bucket ACK
  name: s3-bucket-ack
spec:
  schematic:
    cue:
      template: |
        output: {
        	apiVersion: "s3.services.k8s.aws/v1alpha1"
        	kind:       "Bucket"
        	metadata: {
            name: "\(parameter.name)"
            annotations: {
              "services.k8s.aws/region": "\(parameter.region)"
              "argocd.argoproj.io/sync-options": "Ignore=true,SkipDryRunOnMissingResource=true"
            }
          }
        	spec: name: "\(parameter.name)"
        }
        parameter: {
        	name:   string
        	region: string
        }
  workload:
    type: autodetects.core.oam.dev

