apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-git-credentials
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: flux-git-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: "{{ `{{ .username }}` }}"
        password: "{{ `{{ .token }}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: git-credentials
        property: GIT_USERNAME
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: token
      remoteRef:
        key: git-credentials
        property: GIT_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-ssh-credentials
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: flux-ssh-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        identity: "{{ `{{ .ssh_private_key }}` }}"
        identity.pub: "{{ `{{ .ssh_public_key }}` }}"
        known_hosts: "{{ `{{ .known_hosts }}` }}"
  data:
    - secretKey: ssh_private_key
      remoteRef:
        key: git-ssh-credentials
        property: SSH_PRIVATE_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: ssh_public_key
      remoteRef:
        key: git-ssh-credentials
        property: SSH_PUBLIC_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: known_hosts
      remoteRef:
        key: git-ssh-credentials
        property: KNOWN_HOSTS
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None