apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-oidc
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: keycloak-oidc
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client-id
      remoteRef:
        key: {{ .Values.aws_cluster_name }}/keycloak-clients
        property: ARGO_WORKFLOWS_CLIENT_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret-key
      remoteRef:
        key: {{ .Values.aws_cluster_name }}/keycloak-clients
        property: ARGO_WORKFLOWS_CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
