vela-core:
  nodeSelector:
    karpenter.sh/nodepool: system
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"

cluster-gateway:
  nodeSelector:
    karpenter.sh/nodepool: system
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"

workflow:
  nodeSelector:
    karpenter.sh/nodepool: system
  tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"
