externalSecret:
  enabled: true
  clusterName: peeks-spoke-prod
  secretStoreRefKind: ClusterSecretStore
  secretStoreRefName: aws-secrets-manager
  secretManagerSecretNamePrefix: peeks
  server: remote
