apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-dev
  namespace: argocd
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 2.0.2
    helm:
      releaseName: crossplane
      values: |
        args: []
  destination:
    name: 'dev-cluster'
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
