domain_name: cnoe.io
resource_prefix: peeks

repo:
  url: https://github.com/aws-samples/appmod-blueprints
  revision: main
  path: bootstrap
  basepath: gitops/fleet/

clusters:
  hub:
    name: cnoe-ref-impl
    region: us-west-2
    environment: control-plane
    auto_mode: true
    addons:
      enable_ingress_class_alb: true
      enable_argo_rollouts: false
      enable_kyverno_policies: false
      enable_metrics_server: false
      enable_kyverno: false
      enable_kyverno_policy_reporter: false
      enable_ingress_nginx: true
      enable_argocd: true
      enable_argo_workflows: true
      enable_backstage: false
      enable_kargo: true
      enable_keycloak: true
      enable_gitlab: true
      enable_cert_manager: true
      enable_external_secrets: true
      enable_ack_iam: true
      enable_ack_eks: false
      enable_ack_ec2: false
      enable_ack_efs: false
      enable_kro: false
      enable_kro_eks_rgs: false
      enable_mutli_acct: false
      enable_kubevela: false
      enable_ack_s3: false
      enable_aws_efs_csi_driver: false
      enable_aws_for_fluentbit: false
      enable_cni_metrics_helper: false
      enable_cw_prometheus: false
      enable_external_dns: false
      enable_kube_state_metrics: false
      enable_opentelemetry_operator: false
      enable_prometheus_node_exporter: false
  spoke1:
    name: spoke-dev
    region: us-west-2
    environment: dev
    auto_mode: true
    addons:
      enable_argocd: false
      enable_ack_iam: false
      enable_ack_eks: false
      enable_ack_ec2: false
      enable_external_secrets: false
      enable_metrics_server: false
      enable_kro: false
      enable_ack_efs: false
      enable_aws_efs_csi_driver: false
      enable_aws_for_fluentbit: false
      enable_cert_manager: false
      enable_external_dns: false
      enable_opentelemetry_operator: false
      enable_kyverno: false
      enable_kyverno_policy_reporter: false
      enable_kyverno_policies: false
      enable_cni_metrics_helper: false
      enable_kube_state_metrics: false
      enable_prometheus_node_exporter: false
      enable_prometheus_scraper: false
      enable_cw_prometheus: false
      enable_kro_eks_rgs: false
      enable_mutli_acct: false
      enable_ingress_class_alb: false
      enable_argo_rollouts: false
      enable_ingress_nginx: false
      enable_gitlab: false
      enable_keycloak: false
      enable_argo_workflows: false
      enable_kargo: false
      enable_backstage: false
  spoke2:
    name: spoke-prod
    region: us-west-2
    environment: prod
    auto_mode: true
    addons:
      enable_argocd: false
      enable_ack_iam: false
      enable_ack_eks: false
      enable_ack_ec2: false
      enable_external_secrets: false
      enable_metrics_server: false
      enable_kro: false
      enable_ack_efs: false
      enable_aws_efs_csi_driver: false
      enable_aws_for_fluentbit: false
      enable_cert_manager: false
      enable_external_dns: false
      enable_opentelemetry_operator: false
      enable_kyverno: false
      enable_kyverno_policy_reporter: false
      enable_kyverno_policies: false
      enable_cni_metrics_helper: false
      enable_kube_state_metrics: false
      enable_prometheus_node_exporter: false
      enable_prometheus_scraper: false
      enable_cw_prometheus: false
      enable_kro_eks_rgs: false
      enable_mutli_acct: false
      enable_ingress_class_alb: false
      enable_argo_rollouts: false
      enable_ingress_nginx: false
      enable_gitlab: false
      enable_keycloak: false
      enable_argo_workflows: false
      enable_kargo: false
      enable_backstage: false