domain_name: cnoe.io
resource_prefix: peeks

repo:
  url: https://github.com/aws-samples/appmod-blueprints
  revision: main
  path: bootstrap
  basepath: gitops/fleet/

clusters:
  hub:
    name: hub
    region: us-west-2 # replaced by deploy.sh
    kubernetes_version: 1.32
    environment: control-plane
    tenant: control-plane
    auto_mode: true
    addons:
      enable_ingress_class_alb: true
      enable_argocd: true
      enable_argo_events: true
      enable_argo_rollouts: true
      enable_argo_workflows: true
      enable_kyverno_policies: true
      enable_metrics_server: true
      enable_kyverno: true
      enable_kyverno_policy_reporter: true
      enable_ingress_nginx: true
      enable_backstage: true
      enable_kargo: true
      enable_keycloak: true
      enable_gitlab: true
      enable_cert_manager: true
      enable_external_secrets: true
      enable_ack_iam: true
      enable_ack_eks: true
      enable_ack_ec2: true
      enable_ack_ecr: true
      enable_ack_efs: false
      enable_ack_s3: true
      enable_ack_dynamodb: true
      enable_crossplane: true
      enable_crossplane_aws: true
      enable_kro: true
      enable_kro_manifests: true
      enable_mutli_acct: true
      enable_kubevela: true
      enable_jupyterhub: true
      enable_kubeflow: true
      enable_mlflow: true
      enable_spark_operator: true
      enable_airflow: true
      enable_aws_efs_csi_driver: false
      enable_aws_for_fluentbit: false
      enable_cni_metrics_helper: false
      enable_cw_prometheus: false
      enable_external_dns: false
      enable_kube_state_metrics: false
      enable_opentelemetry_operator: false
      enable_prometheus_node_exporter: false
  spoke1:
    name: spoke-dev
    region: us-west-2 # replaced by deploy.sh
    kubernetes_version: 1.32
    environment: dev
    tenant: tenant1
    auto_mode: true
    addons:
      enable_argocd: false
      enable_argo_events: false
      enable_argo_rollouts: true
      enable_argo_workflows: false
      enable_ack_iam: true
      enable_ack_eks: true
      enable_ack_ec2: true
      enable_ack_ecr: true
      enable_ack_s3: true
      enable_ack_efs: false
      enable_ack_dynamodb: true
      enable_crossplane: true
      enable_crossplane_aws: true
      enable_external_secrets: true
      enable_flux: true
      enable_metrics_server: true
      enable_kro: false
      enable_aws_efs_csi_driver: false
      enable_aws_for_fluentbit: false
      enable_cert_manager: true
      enable_external_dns: false
      enable_opentelemetry_operator: false
      enable_kubevela: true
      enable_kyverno: true
      enable_kyverno_policy_reporter: false
      enable_kyverno_policies: false
      enable_cni_metrics_helper: false
      enable_kube_state_metrics: false
      enable_prometheus_node_exporter: false
      enable_prometheus_scraper: false
      enable_cw_prometheus: false
      enable_kro_eks_rgs: false
      enable_mutli_acct: false
      enable_ingress_class_alb: false
      enable_ingress_nginx: true
      enable_gitlab: false
      enable_keycloak: false
      enable_kargo: false
      enable_backstage: false
      enable_platform_manifests: true
  spoke2:
    name: spoke-prod
    region: us-west-2 # replaced by deploy.sh
    kubernetes_version: 1.32
    environment: prod
    tenant: tenant1
    auto_mode: true
    addons:
      enable_argocd: false
      enable_argo_events: false
      enable_argo_rollouts: true
      enable_argo_workflows: false
      enable_ack_iam: true
      enable_ack_eks: true
      enable_ack_ec2: true
      enable_ack_ecr: true
      enable_ack_efs: false
      enable_ack_s3: true
      enable_ack_dynamodb: true
      enable_crossplane: true
      enable_crossplane_aws: true
      enable_external_secrets: true
      enable_flux: true
      enable_metrics_server: true
      enable_kro: false
      enable_aws_efs_csi_driver: false
      enable_aws_for_fluentbit: false
      enable_cert_manager: true
      enable_external_dns: false
      enable_opentelemetry_operator: false
      enable_kubevela: true
      enable_kyverno: true
      enable_kyverno_policy_reporter: false
      enable_kyverno_policies: false
      enable_cni_metrics_helper: false
      enable_kube_state_metrics: false
      enable_prometheus_node_exporter: false
      enable_prometheus_scraper: false
      enable_cw_prometheus: false
      enable_kro_eks_rgs: false
      enable_mutli_acct: false
      enable_ingress_class_alb: false
      enable_ingress_nginx: true
      enable_gitlab: false
      enable_keycloak: false
      enable_kargo: false
      enable_backstage: false
      enable_platform_manifests: true
