---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-oidc-secret
  namespace: mlflow
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: keycloak-clients
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        MLFLOW_CLIENT_SECRET: "{{ `{{.MLFLOW_CLIENT_SECRET}}` }}"
  data:
    - secretKey: MLFLOW_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.global.resourcePrefix }}-hub/keycloak-clients
        property: MLFLOW_CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None