apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: Configures K8s ingress and service to enable web traffic for your service
  name: ingress
spec:
  schematic:
    cue:
      template: |
        parameter: {
        	// +usage=Specify the domain you want to expose
        	domain: string
        	// +usage=Specify the mapping relationship between the http path and the workload port
        	http: [string]: int
        }
        
        // trait template can have multiple outputs in one trait
        outputs: service: {
        	apiVersion: "v1"
        	kind:       "Service"
        	metadata: name: context.name
        	spec: {
        		selector: "app.oam.dev/component": context.name
        		ports: [
        			for k, v in parameter.http {
        				port:       v
        				targetPort: v
        			},
        		]
        	}
        }
        
        outputs: ingress: {
        	apiVersion: "networking.k8s.io/v1"
        	kind:       "Ingress"
        	metadata: {
        		name: context.name
        	}
        	spec: {
        		rules: [{
        			host: parameter.domain
        			http: {
        				paths: [
        					for k, v in parameter.http {
        						path:     k
        						pathType: "Prefix"
        						backend: service: {
        							name: context.name
        							port: number: v
        						}
        					},
        				]
        			}
        		}]
        	}
        }
